theme: jekyll-theme-cayman
# SITE CONFIGURATION
baseurl: ""
url: "https://rajk2888.github.io/Rajkumar_Portfolio.github.io/"

# THEME-SPECIFIC CONFIGURATION
title: Welcome to Rajkumar Kuppuswami Master in Data science                                   # site's title
description: "Feel free to bookmark this to keep an eye on my projects updates"      # used by search engines
avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Data Science Portfolio<br/>
                  Rajkumar Kuppuswami # Change Blog header text
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  Copyright 2020

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

#theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
